version: 2
defaults: &defaults
  machine:
    image: circleci/classic:edge

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: ./scripts/ci

workflows:
  version: 2
  default-workflow:
    jobs:
      - test
