#!/bin/bash

git submodule init
cp .git/config /tmp/config
sed 's/git.github.com:mauricioszabo.repl-tooling/https:\/\/github.com\/mauricioszabo\/repl-tooling.git/' /tmp/config > .git/config
git submodule update

docker build -f integration/Dockerfile -t atom .
docker run --rm -it -u root -v`pwd`:/work atom sh -c 'npm install && npx shadow-cljs release dev --source-maps'
./scripts/run-test-server

git clone https://github.com/JunoLab/atom-ink.git ink
docker run --rm -it -u root -v`pwd`/ink:/work atom sh -c 'cd /work && npm install'

docker run --rm \
    -it \
    --network=host \
    -u root \
    -v ~/junit/test-results.xml:/tmp/junit \
    -v`pwd`:/work \
    -v `pwd`/integration/chlorine-tests:/root/.atom/packages/chlorine-tests \
    -v `pwd`:/root/.atom/packages/chlorine \
    -v `pwd`/ink:/root/.atom/packages/ink \
    atom
