#!/bin/bash

echo "--- LOAD IMAGE ---"
docker load -i docker-image.img

echo "--- FIRE UP INTEGRATION TESTS ---"
docker run --rm \
    -it \
    --network=host \
    -u root \
    -v ~/junit/test-results.xml:/tmp/junit \
    atom
