#!/bin/bash
set -e

echo "--- LOAD IMAGE ---"
docker load -i docker-image.img

echo "--- PUBLISH ---"
docker run -v ~/project:/proj atom cp -av /work /proj
sudo chown circleci -R work
cd work
git tag `echo "$CIRCLE_BRANCH-source" | sed s/release-//`

git config --global user.email "circleci@chlorine.plugin"
git config --global user.name "CircleCI Automated Build"
git checkout -b release-prepare-DELETE-THIS
git rm -r src integration scripts
git add -f lib/cmds.js lib/main.js
git commit -m 'Compiled version for release'
git tag `echo $CIRCLE_BRANCH | sed s/release-//`

git remote add gh git@github.com:mauricioszabo/atom-chlorine.git
git remote add gitlab git@gitlab.com:clj-editors/atom-chlorine.git
echo "Push source tag to GitLab"
git push gitlab `echo "$CIRCLE_BRANCH-source" | sed s/release-//`
echo "Push release tag to GitHub"
git push gh `echo $CIRCLE_BRANCH | sed s/release-//`
