#!/bin/bash

echo "--- LOAD IMAGE ---"
docker load -i docker-image.img

echo "--- PUBLISH ---"
docker run \
  --network=host \
  -v ~/.ssh:/root/.ssh \
  -e CIRCLE_BRANCH=$CIRCLE_BRANCH \
  atom \
  /work/scripts/ci-prepare-release
