#!/bin/bash

read -p "Remember to tag a version with the current source code (git tag vX.X.X-source)"

lein run -m shadow.cljs.devtools.cli --npm release dev
git rm -r src
git rm -r integration
git rm -r scripts
git add -f lib/main.js

echo "Done. Now, prepare the tag, and publish with apm publish --tag"
