#!/bin/bash

rm -Rf integration/fixture-app/target/

if [ "$1" == "node" ]; then
    cd integration/chlorine-test && npm install && nohup npx shadow-cljs watch dev &
else
    docker run -d \
        --network=host \
        -it \
        -u root \
        -v`pwd`:/work \
        atom \
        sh -c 'cd /work/integration/chlorine-test && npm install && npx shadow-cljs watch dev'
fi
