#!/bin/bash

#rm -Rf integration/fixture-app/target/
#cd integration/fixture-app && ./scripts/repl &
cd /work/integration/chlorine-tests && npm install && npx shadow-cljs watch tests &
ln -s /work/integration/chlorine-tests /root/.atom/packages/chlorine-tests

for n in {1..35}; do
  ls integration/chlorine-tests/lib/main.js &>/dev/null && break
  echo "Test plug-in not compiled yet, waiting... ($n)"
  sleep 15
done

ls integration/chlorine-tests/lib/main.js &>/dev/null || (docker logs test-server && exit 1)
sh -c 'sleep 240 && killall atom' &

nohup ffmpeg -video_size 1024x768 -f x11grab -i :80.0 /tmp/junit/out.mpg &

atom --no-sandbox --foreground /work/integration/chlorine-tests
result=$?

echo -e "(System/exit 0)\n" | nc localhost 3333
exit $result
