#!/bin/bash

#rm -Rf integration/fixture-app/target/
#cd integration/fixture-app && ./scripts/repl &
for n in {1..15}; do
  ls integration/fixture-app/target/main.js &>/dev/null && break
  echo "Fixture APP not compiled yet, waiting..."
  sleep 10
done

node integration/fixture-app/target/main.js &
ffmpeg -video_size 1024x768 -f x11grab -i :80.0 /tmp/junit/out.mpg &

atom --foreground /work/integration/chlorine-test
result=$?

echo -e "(System/exit 0)\n" | nc localhost 3333
exit $result
